### ISSUE TITLE
Improvement suggestion: Add required Windows user rights to the documentation

### ISSUE THREAD

**Issue by aryoda** [jwijffels/taskscheduleR#1]
Great idea, this package, I currently solve this via an externel scheduler + a database "job queue" table.

Would it be possible to add the required user right under which the R session must be run so that the scheduled tasks are accessible (and can be modified)?

With "user rights" I mean the required Windows groups, roles etc. ...

Thanks :-)

**Comment by jwijffels** [comment]
I could add the /RU and /RP argument (user context + password) which is available https://github.com/jwijffels/taskscheduleR/blob/master/inst/docs/schtasks.pdf
That would be usesfull if you want to schedule a script under another user and you know the password of that user

**Comment by aryoda** [comment]
Adding these parameters is definitely helpful!

What I meant in my enhancement request is to improve the documentation by specifying the preconditions for using the package.

A helpful link is here:

[https://technet.microsoft.com/en-us/library/cc785125%28v=ws.10%29.aspx](https://technet.microsoft.com/en-us/library/cc785125%28v=ws.10%29.aspx)

> By default, to schedule a task, you must be a member of the Administrators, Backup Operators, or Server Operators group on the local computer.

I do not know more (never tried it without admin rights myself)

**Comment by jwijffels** [comment]
I'm not sure about that. The link states 'Windows Server 2003, Windows Server 2003 R2, Windows Server 2003 with SP1, Windows Server 2003 with SP2'

If I launch a task, it is run as my user 'BNOSAC\Jan' (my default), not as administrator.

```
tasks <- taskscheduler_ls()
str(tasks)
table(tasks[["Run As User"]])
```

Can you check on a computer without admin rights.

**Comment by jwijffels** [comment]
I have added an argument called schtasks_extra which allows you to pass on other arguments to the scheduling. Like e.g. /RU and /RP - e.g. if you want to schedule a process on another computer or with another user for which you know the password.

I'll check your remark about rights when I am working on a computer without admin rights. But as far as I know, schtasks.exe will launch a task as the user which is logged into the computer. That means that you don't need to be admin to schedule a task (maybe this is the case on Windows Server but not on Windows 7 I believe). But I'll doublecheck on another machine.

**Comment by jwijffels** [comment]
added in readme that this is for people with admin rights as indicated also at https://msdn.microsoft.com/en-us/library/windows/desktop/bb736357(v=vs.85).aspx

**Comment by aryoda** [comment]
Thanks :-)
