### ISSUE TITLE
issue with monthly task running

### ISSUE THREAD

**Issue by datafaust** [jwijffels/taskscheduleR#13]
trying to run monthly task scheduling with the following:

myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")
taskscheduler_create(taskname = "test_myscript_monthly", 
                     rscript = myscript, 
                     schedule = "MONTHLY", 
                     months = "*",
                     days = "THU",
                     startdate = format(as.Date(Sys.Date()) + 2, '%m/%d/%Y'))

but got the following error:

Warning: running command 'schtasks /Create /TN "test_myscript_monthly" /TR "cmd /c C:/PROGRA~1/R/R-33~1.1/bin/Rscript.exe C:/Users/lopezf/Documents/R/win-library/3.3/taskscheduleR/extdata/helloworld.R  >> C:/Users/lopezf/Documents/R/win-library/3.3/taskscheduleR/extdata/helloworld.log 2>&1" /SC MONTHLY /ST 12:21 /SD "11/05/2016" /D THU /M * ' had status 16389
[1] "ERROR: Invalid value for /D option."     "Type \"SCHTASKS /CREATE /?\" for usage."
attr(,"status"

my 'weekly', 'daily' and 'once' work fine. Any ideas what it might be? Thank you!

**Comment by jwijffels** [comment]
For MONTHLY, you have to specify days as either one of 1 up to 31 instead of THU. 
More information: https://github.com/bnosac/taskscheduleR/blob/master/inst/docs/schtasks.pdf
Can you try that.

**Comment by datafaust** [comment]
worked like a charm!

myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")
taskscheduler_create(taskname = "test_myscript_monthly", 
                     rscript = myscript, 
                     schedule = "MONTHLY", 
                     months = "*",
                     days = '3',
                     startdate = format(as.Date(Sys.Date()) + 2, '%m/%d/%Y'))

thanks a bunch!!!!!
