### ISSUE TITLE
Question about running ONIDLE task

### ISSUE THREAD

**Issue by datafaust** [jwijffels/taskscheduleR#14]
Hey,

So now I'm trying to run the ONIDLE tasking to try and have a task run at 15 minute intervals; my understanding is that ONIDLE would allow me to do this. I've been using the following code. The task schedules but then when I check tasks <- taskscheduler_ls() I notice that the "next running time" = NA and the task doesn't run at all. Any ideas what I might be doing wrong? Thank you!

**myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")
taskscheduler_create(taskname = "myscript", 
                     rscript = myscript, 
                     schedule = "ONIDLE",
                     startdate = format(as.Date(Sys.Date()), '%m/%d/%Y'),
                     starttime = "21:40",
                     idletime = 15)**

**Comment by jwijffels** [comment]
ONIDLE is when your computer does nothing, in this case you specified a script to run when your computer does 15 minutes nothing (you are not actively working on your computer).

Have you tried MINUTE. As in

```
myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")
taskscheduler_create(taskname = "myscript",
                     rscript = myscript,
                     schedule = "MINUTE",
                     startdate = format(as.Date(Sys.Date()), '%m/%d/%Y'),
                     starttime = "21:40",
                     modifier = 15)
```

**Comment by datafaust** [comment]
That was my misunderstanding, thank you so much this worked perfectly!

**Comment by jwijffels** [comment]
thanks for the questions, i've updated the documentation with more examples on the usage
