### ISSUE TITLE
Probelm scheduling a weekly task

### ISSUE THREAD

**Issue by nirsisense** [jwijffels/taskscheduleR#15]
Hi,
I'm sending these 2 commands:
taskscheduler_create(taskname = "indices.task", rscript = indices.script, 
                     schedule = "DAILY", starttime = "09:10", startdate = format(Sys.Date()+1, "%m/%d/%Y"))

taskscheduler_create(taskname = "lowest.task", rscript = lowtea.script, 
                     schedule = "WEEKLY", starttime = "07:10", days = 'SUN')
first task created successfully
and the second return the following error:
[1] "ERROR: Value for '/TR' option cannot be more than 261 character(s)."
attr(,"status")
[1] 16389

**Comment by jwijffels** [comment]
this looks like the error message indicates that the full path to your file is longer than 261 characters. 
Can you print out `lowtea.script` + How long is lowtea.script as in `nchar(lowtea.script)`
Solution is either to put your scripts into a not such a long folder name. Apparently schtasks.exe has this limit, which I wasn't aware off.

**Comment by nirsisense** [comment]
> nchar(lowtea.script)
[1] 103

**Comment by nirsisense** [comment]
> lowtea.script
[1] "C:/Users/nir.regev.PROD/Documents/R/win-library/3.3/taskscheduleR/extdata/nth_lowest_tea_index_weekly.R"

**Comment by nirsisense** [comment]
After trimming the script name I get a different error:
taskscheduler_create(taskname = "lowest.task", rscript = lowtea.script, 
                     schedule = "WEEKLY", starttime = "07:10", days = 'SUN')
[1] "ERROR: Incorrect Start Date."
attr(,"status")
[1] 16389

the script was trimmed to this
> lowtea.script
[1] "C:/Users/nir.regev.PROD/Documents/R/win-library/3.3/taskscheduleR/extdata/lowest_tea.R"

**Comment by nirsisense** [comment]
and after adding the start date everything ok
thanks

**Comment by jwijffels** [comment]
My suggestion would be not to put your scripts in "C:/Users/nir.regev.PROD/Documents/R/win-library/3.3/taskscheduleR/extdata" but somewhere else, say "C:/Users/projectxyz"
Because basically the following task is given to the \TR argument of schtasks.exe and probably that is longer than what is apparently allowed by windows. Can you check that.
```
rscript <- lowtea.script
rscript_args <- ""
task <- sprintf("cmd /c %s %s %s >> %s.log 2>&1", 
                file.path(Sys.getenv("R_HOME"), "bin", "Rscript.exe"), 
                rscript, paste(rscript_args, collapse = " "), 
                tools::file_path_sans_ext(rscript))
task
nchar(task)
```

**Comment by nirsisense** [comment]
230

**Comment by jwijffels** [comment]
Just put your scripts into a shorter folder as in "C:/Users/projectxyz" and it will be solved.
