### ISSUE TITLE
Running task once to test

### ISSUE THREAD

**Issue by nburdett19** [jwijffels/taskscheduleR#17]
Hello, 

I have the following to create a task running an R file with a simple read.xlsx and write.xlsx command to test the scheduling aspect of the package. Once i run this, i get the "SUCCESS: The scheduled task \"testing123testing\" has successfully been created." message, but nothing happens in the folders i would expect the .xlsx output and the log files. Could you help?

taskscheduler_create(taskname = "testing123testing", 
                     rscript = "C:/Users/<my user name>/Documents/R/win-library/3.3/taskscheduleR/extdata/scheduled-automation-test.R",
                     schedule = "ONCE",
                     starttime = format(Sys.time() +62,"%H:%M"),
                     startdate = format(Sys.Date(),"%d/%m/%Y",
                     Rexe = "C:/Program Files/R/R-3.3.2/bin/Rscript.exe"))

Thanks!!

-Nick

**Comment by jwijffels** [comment]
go to C:/Users//Documents/R/win-library/3.3/taskscheduleR/extdata
and look at the scheduled-automation-test.log file

**Comment by nburdett19** [comment]
Hi Thanks for your quick response. I got my task to run and everything seems to be in working order.
