### ISSUE TITLE
Unifying with cronR

### ISSUE THREAD

**Issue by stanstrup** [jwijffels/taskscheduleR#18]
Hi,

this is very cool but wouldn't it be possible to unify with https://github.com/bnosac/cronR?
So you would have a common platform independant way to make tasks.

**Comment by jwijffels** [comment]
Yes, that would be nice. But this would require a whole rewrite and it is not top of my todo list.

**Comment by jwijffels** [comment]
Closing this as not a priority.
I'm open to pull requests if you plan to implement this yourself.
