### ISSUE TITLE
Run While Logged Out

### ISSUE THREAD

**Issue by ericbrownaustin** [jwijffels/taskscheduleR#19]
Is it possible to use taskscheduleR to select security options for running tasks while logged out like in Task Scheduler?

**Comment by jwijffels** [comment]
have you tried?

**Comment by jwijffels** [comment]
There is an argument called schtasks_extra where you can pass further arguments to schtasks.exe as explained at https://github.com/bnosac/taskscheduleR/blob/master/inst/docs/schtasks.pdf 
Do try that out if this is what you are looking for. Closing this.
