### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Patrikios** [jwijffels/taskscheduleR#2]
Hi while installing the package 

```
library(devtools)
devtools::install_github("jwijffels/taskscheduleR")
```

the following error message is returned:

```
Downloading GitHub repo jwijffels/taskscheduleR@master
from URL https://api.github.com/repos/jwijffels/taskscheduleR/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name
```

How can I resolve this? 
For solutions like http://stackoverflow.com/questions/17783686/solution-how-to-install-github-when-there-is-a-proxy I need special configuration.

**Comment by jwijffels** [comment]
this is probably related to a proxy setting of your computer. you should ask that question at the authors of the devtools package.

**Comment by jwijffels** [comment]
FYI. Added other installation option to README

```

install.packages('data.table')
install.packages('knitr')
install.packages("taskscheduleR", repos = "http://www.datatailor.be/rcube", type = "source")
```

**Comment by Patrikios** [comment]
Thnx for the alternative!

**Comment by Patrikios** [comment]
The instalationfrom the alternative source was successful however the package doesnt work for me. Im not sure if this is the right place for an additional question but so be it, if not please repost

I try to run in order to test it the example R file Hello World::

    myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")


    taskscheduler_create(taskname = "myfancyscript", rscript = myscript, 
                     schedule = "ONCE", starttime = format(Sys.time() + 62, "%H:%M"))

In 62 secs goes on a black window up and in a sec disapears. Thats it the codes messages do not appear in the console. I also created my own script that write a .csv doesn`t work neither. Is there something that I neglected in the code or in the settings?

**Comment by jwijffels** [comment]
please make a new issue.
