### ISSUE TITLE
Path name with spaces

### ISSUE THREAD

**Issue by wmorris1** [jwijffels/taskscheduleR#20]
Can the package be updated to allow spaces in the path name to the script? For example, here is my code:
Midlandscript <- file.path("S:/Weather Forecasts/R programming", "Midland_Daily.R")
taskscheduler_create(taskname = "myMidlandscript", rscript = Midlandscript, 
 schedule = "ONCE", starttime = format(Sys.time() + 5, "%H:%M"))

However, the S drive is a shared folder, and my IT folks do not want to add another folder (with no spaces) for some unknown reason. Thus, I can not change the folder name to something like this: 
Midlandscript <- file.path("S:/Weather_Forecasts/R_programming", "Midland_Daily.R")

An option is using my hard drive (something like "C:\temp"), but that is not backed up like a network drive. 

Thank you.

**Comment by jwijffels** [comment]
Fixed
