### ISSUE TITLE
Periodic_scheduling doesn't seem to work

### ISSUE THREAD

**Issue by BledarKulemani** [jwijffels/taskscheduleR#21]
I created a script that adds a line to a text file. I then scheduled the task to run on "MINUTE" with modifier = 2 (every two minutes). I expect to see lines added to the text file every two minutes, but that is not the case. Any help would be appreciated.

Best, Bledar.

**Comment by jwijffels** [comment]
You need to provide your code + how you launch the script + the log in order to get usefull help on your question

**Comment by jwijffels** [comment]
Closing this as no feedback in 2 weeks & unreproducible.
