### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by germayneng** [jwijffels/taskscheduleR#22]
Hi, thank you for this fantastic script. So i tested this using a simple script that contains this line:
`print("hello world")`

so i scheduled it for minutely. But on the R console, I cant see any thing ran. 

Then i tried another script: 

```
library(data.table)
setwd("D:/")
test <- data.frame(a = 1, b= 2, c=3)
fwrite(test,"deleteme.csv")

```

Again, nothing happens. Can you help me because there are some task i wish to automate. Question 2: Also does this work when R studio is not open or only when R studio is opened.

Everything is done using the add-in

**Comment by germayneng** [comment]
checking at D:\R-3.3.2\library\taskscheduleR\extdata
there is no log file. So the R file is not ran at all

============================================
Also checking  tasks <- taskscheduler_ls()

one min before, 
![capture](https://user-images.githubusercontent.com/22788747/28061607-c5c397dc-665d-11e7-9681-e2e5a1514cda.JPG)



one minute later, the status is 'Could not start'
![capture](https://user-images.githubusercontent.com/22788747/28061550-908429c4-665d-11e7-822d-f635ac83d312.JPG)

**Comment by jwijffels** [comment]
You shouldn't see anything at the R console if it ran. The R process is ran through the Windows Task scheduler - hence the name of the package.
The log file is at the folder location where your .R file is, this is probably not at D:\R-3.3.2\library\taskscheduleR\extdata, unless you've put your .R file there.

Yes this works if RStudio is not open but does not work if your computer has no power :) or if you don't have rights to schedule commands in the Windows taskscheduler.

**Comment by germayneng** [comment]
Hi @jwijffels 

I managed to get it to work properly. So when the script is ran, a black cmd window will pop up for a quick second and disappear. 

Another doubt:
So for example, if i schedule it for monthly at 10am. This meant that so long the computer is log in before 10am next month, the script will run? Therefore we can shut down the computer as per normal?

**Comment by jwijffels** [comment]
Just try it out and you'll find out.
