### ISSUE TITLE
I can only get "ONCE" to work, nothing else

### ISSUE THREAD

**Issue by kjell21** [jwijffels/taskscheduleR#24]
I'm running a script.  Whenever I use the examples, a log file is only created for whenever I run "ONCE".  The cmd pops up for a second and everything. If I run anything else, like "MINUTE", cmd does not pop up and it does not run. And creates no log file.  Can you help me out?

**Comment by jwijffels** [comment]
You need to provide code otherwise I can't help you.

**Comment by kjell21** [comment]
![image](https://user-images.githubusercontent.com/25596605/29241485-68e380d0-7f40-11e7-998b-6e57020d580d.png)

**Comment by kjell21** [comment]
This code works fine.  CMD popped up right at 09:26... now on to the problem section

**Comment by kjell21** [comment]
![image](https://user-images.githubusercontent.com/25596605/29241522-178aa08c-7f41-11e7-9a1d-eba8f7cf6b34.png)

**Comment by kjell21** [comment]
It is now 09:33, and no log appears and no cmd opened up, even though it said that the script was created.

**Comment by kjell21** [comment]
![image](https://user-images.githubusercontent.com/25596605/29241615-fc016a92-7f42-11e7-9228-a613e495447f.png)

**Comment by kjell21** [comment]
same issue, no log, no cmd.

**Comment by jwijffels** [comment]
I believe you forgot to add the argument startdate in the format of the locale of your computer. The default of that is` format(Sys.Date(), "%d/%m/%Y")`. Maybe you need to change that format to your system locale by switching years/months/date order of that format statement. (see the README where this is mentionned: E.g. in the US %m/%d/%Y)

**Comment by kjell21** [comment]
Yeah, that's it.  thank you.  one more question, how do I put an end time in?  I want it to run once a minute for 2 hours then stop.

thank you

**Comment by jwijffels** [comment]
Good this is solved. Can you put your other question in a new issue.

**Comment by BrightsizeLife** [comment]
I can only get "ONCE" to work too. It will not run when I shift to "MINUTE". If I try to force it to run with taskcheduler_runnow(), it works perfectly. Any idea of how I can remedy this? If so, this will help a million.
Thanks! 
p.s., the ultimate goal is to switch to "DAILY"

```
myscript <- paste0(getwd(),"/Test_2.R")

runon <- format(Sys.time() + 62, "%H:%M")

taskscheduler_create(taskname = "myfancyscript",
 rscript = myscript, schedule = "MINUTE",
 starttime = runon, startdate = format(Sys.Date(), "%d/%m/%Y"))

[1] "SUCCESS: The scheduled task \"myfancyscript\" has successfully been created."

taskcheduler_runnow("myfancyscript")

SUCCESS: Attempted to run the scheduled task "myfancyscript".
```

**Comment by jwijffels** [comment]
Change startdate format to us format if you are in us. See readme + the solution provided in this issue
