### ISSUE TITLE
Is there an endtime function?

### ISSUE THREAD

**Issue by kjell21** [jwijffels/taskscheduleR#25]
I'm trying to run a script once every minute for 2 hours and then stop.  I couldn't find any examples of this in your examples.  Is it possible to set an endtime in taskscheduleR?

**Comment by jwijffels** [comment]
The enddate & endtime functionality is not explicitely mapped on to taskscheduler_create, but it can be done with the `schtasks_extra` argument.
The taskscheduleR package basically sends calls to schtasks.exe. The documentation of this executable is at https://github.com/bnosac/taskscheduleR/blob/master/inst/docs/schtasks.pdf 
If you look there it has the arguments /ET and /ED so if you provide `schtasks_extra` = '/ET 14:15 /ED 08/16/2017' when you call `taskscheduler_create`, this might be what you are looking for. You could also have a look at the /DU argument which you can also pass to schtasks_extra, which is a duration of a task. See the documentation of https://github.com/bnosac/taskscheduleR/blob/master/inst/docs/schtasks.pdf  on how to provide that argument.
