### ISSUE TITLE
taskscheduler_ls() fread issue

### ISSUE THREAD

**Issue by cinkie** [jwijffels/taskscheduleR#26]
`> tasks <- taskscheduler_ls()`

Error in data.table::fread(f, ...) : 
  Expecting 28 cols, but line 147 contains text after processing all cols. Try again with fill=TRUE. Another reason could be that fread's logic in distinguishing one or more fields having embedded sep=',' and/or (unescaped) '\n' characters within unbalanced unescaped quotes has failed. If quote='' doesn't help, please file an issue to figure out if the logic could be improved.

**Comment by jwijffels** [comment]
Please use the latest version from https://github.com/bnosac/taskscheduleR, not from CRAN
