### ISSUE TITLE
can't determine location of log file...

### ISSUE THREAD

**Issue by bitsmashtrader** [jwijffels/taskscheduleR#27]
can we...?

should be easy to add as a param. i'll do later perhaps.

**Comment by jwijffels** [comment]
It's in the folder where your R script is located.

**Comment by bitsmashtrader** [comment]
sorry if i was a little ambiguous, what I meant was that it would be nice/helpful to be able to specify the location of the log file. (I prefer all of mine in a /log directory with a date/time stamp in the file name.)

i made a local fork and added a logPath parameter to the function that defaulted to the hardwired location as before.

**Comment by jwijffels** [comment]
if you have a local fork which adds the date/time stamp and the folder to a location which you like, feel free to make a pull request
