### ISSUE TITLE
During installation, the following error occurred :

### ISSUE THREAD

**Issue by dialektike** [jwijffels/taskscheduleR#28]
> install.packages("taskscheduleR", repos = "http://www.datatailor.be/rcube", type = "source") 

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning in install.packages : 
package ‘taskscheduleR’ is not available (for R version 3.4.1)

**Comment by jwijffels** [comment]
The warning means basically that package taskscheduleR is not available as a binary windows version on www.datatailor.be. It is only provided as a source package.
It's not an error. Just load the package library(taskscheduleR) and start on scheduling your scripts
