### ISSUE TITLE
schedule MONTHLY

### ISSUE THREAD

**Issue by OliverBLMS** [jwijffels/taskscheduleR#3]
I keep getting an error when selecting MONTHLY schedule.
`taskscheduler_create(taskname = "myfancyscript", rscript = myscript, schedule = "MONTHLY")`

By looking at the source code, this should be autocompleted by default values for startdate, months, days?

`[1] "Fout: ongeldige waarde voor optie /D."     "Typ SCHTASKS /CREATE /? voor de syntaxis. attr(,"status") [1] 16389 Warning message: running command schtasks /Create /TN "myfancyscript" /TR "cmd /c C:/R/R-32~1.3/bin/Rscript.exe c:/R/Libs/taskscheduleR/extdata/helloworld.R >> c:/R/Libs/taskscheduleR/extdata/helloworld.log 2>&1" /SC MONTHLY /ST 15:50 /SD "18/03/2016" /D * /M * had status 16389`

**Comment by jwijffels** [comment]
I believe the syntax for \D is making sure you specify on which day of the month you want it.

`taskscheduler_create(taskname = "myfancyscript", rscript = myscript, schedule = "MONTHLY", days = "1")`

See also https://github.com/jwijffels/taskscheduleR/blob/master/inst/docs/schtasks.pdf
