### ISSUE TITLE
Can not create the task

### ISSUE THREAD

**Issue by sandeshregmi** [jwijffels/taskscheduleR#30]
[1] "ERROR: Invalid value for /D option."    
[2] "Type \"SCHTASKS /CREATE /?\" for usage."
attr(,"status")
[1] 16389

Warning message:
running command 'schtasks /Create /TN "SUAM_4_1" /TR "cmd /c C:/PROGRA~1/R/R-32~1.5/bin/Rscript.exe \"U:/ModelSchedules/taskR.R\"  >> \"U:/ModelSchedules/taskR.log\" 2>&1" /SC MONTHLY /ST 03:00 /SD "2017-11-20" /D * /M * ' had status 16389 
-------------------------------
library(taskscheduleR)
SUAM_4_1_script<- "U:/ModelSchedules/taskR.R"
taskscheduler_create(taskname = "SUAM_4_1", 
                     rscript = SUAM_4_1_script, 
                     schedule = "MONTHLY", 
                     startdate = as.Date(cut(Sys.Date(), "month"))+19,
                     starttime = "03:00"
                     )

**Comment by jwijffels** [comment]
When you use monthly, you have to specify on which day of the month you want to run it. As in

```
taskscheduler_create(taskname = "SUAM_4_1",
                     rscript = SUAM_4_1_script,
                     schedule = "MONTHLY",
                     startdate = format(as.Date(cut(Sys.Date(), "month"))+19, "%d/%m/%Y"),
                     starttime = "03:00",
                     days = "1",
)
```

**Comment by sandeshregmi** [comment]
Thank you.
Is there a way to see the list of scheduled tasks?
