### ISSUE TITLE
create task as system task 

### ISSUE THREAD

**Issue by auenbauer** [jwijffels/taskscheduleR#32]
Using taskscheduleR we run scripts every 5 minutes. Hence every 5 minutes a cmd.exe window shows up and fetches the gui focus. This is very annoying for the user and I wanted to ask if there is a way to eliminate this behavior. This supposedly would not happen if [tasks are created as system tasks](https://stackoverflow.com/a/6568823/7413376).

**Comment by jwijffels** [comment]
Use the `schtasks_extra` argument to pass on other options which are defined at https://github.com/bnosac/taskscheduleR/blob/master/inst/docs/schtasks.pdf

E.g. `schtasks_extra = "/RU SYSTEM /RP yourpassword" `in order to run that as user SYSTEM instead of your own user

**Comment by auenbauer** [comment]
Remark: `schtasks.pdf` points out, that `/RP yourpassword` is not necessary for the system account.
Unfortunately, it seems very difficult to install the R packages correctly as system administrator.

Anyhow, this answers our question. Thank you, @jwijffels. Issue closed.

**Comment by jwijffels** [comment]
If you want to run R code as admin, assuming that you use RStudio, just right-click on the rstudio.exe or R.exe and install the package. Mark that you'll also need to install all the R packages that the R scripts are using as admin.
