### ISSUE TITLE
Start date on Task ScheduleR GUI in Rstudio 

### ISSUE THREAD

**Issue by HamidM6** [jwijffels/taskscheduleR#35]
Today is 5th of April, I am trying to schedule a task by minute starting in five minutes. Start date display on GUI is '2018-04-05' however it does not run until I change it to '2018-05-04'. not sure if this is a bug or it suppose to be this way.

**Comment by jwijffels** [comment]
It's not a bug. See here https://stackoverflow.com/questions/48712955/taskscheduler-runs-once-but-does-not-run-hourly-weekly-daily-etc

**Comment by HamidM6** [comment]
ok, thanks
