### ISSUE TITLE
Update to R 3.4.4

### ISSUE THREAD

**Issue by mrcflckrz** [jwijffels/taskscheduleR#37]
Do you plan on updating your package to R 3.4.4?
We're running this version (with RStudio) on our server and unfortunately I can't install taskscheduleR (whcih I would love to...).

**Comment by jwijffels** [comment]
Which server is that? A Linux server or a Windows?

**Comment by mrcflckrz** [comment]
R runs on a Linux server.

**Comment by jwijffels** [comment]
You need to use the cronr package instead, taskscheduler is for Windows, cronr for Linux/ unix
