### ISSUE TITLE
TaskScheduleR addin is not working

### ISSUE THREAD

**Issue by AlexKost5791** [jwijffels/taskscheduleR#38]
[TaskSchedulaerIssue.pdf](https://github.com/bnosac/taskscheduleR/files/1903864/TaskSchedulaerIssue.pdf)

**Comment by AlexKost5791** [comment]
Steps before I got snapshot for attempt of creating TaskScheduleR for my script "TestScript.R"  this morning:

R>>> "Addins">>>> [Schedule your Rscript] >>>[Choose your script] >>>>[Browse] >>>.
[path]" TestScript.R">>>[Schedule]>>>[Once]>>>[Start date:]>>>>2018-04-12>>>>[Hour start]>>>>09:55>>>[Create task]>>>>[Done]

After black window popped up nothing happened.

R Console read the following:

Details from attached screenshot:
taskscheduleR:::taskschedulerAddin()
Listening on http://127.0.0.1:5924
Creating task schedule: schtasks /Create /TN "TestScript.R" /TR "cmd /c C:/R-34~1.3/bin/Rscript.exe "C:/R-3.4.3/library/taskscheduleR/extdata/TestScript.R" >> "C:/R-3.4.3/library/taskscheduleR/extdata/TestScript.log" 2>&1" /SC ONCE /ST 09:55

**Comment by jwijffels** [comment]
What is logged into the file at C:/R-3.4.3/library/taskscheduleR/extdata/TestScript.log?

**Comment by AlexKost5791** [comment]
Loading required package: methods
Warning message:
package 'miniUI' was built under R version 3.4.4 
Warning message:
package 'data.table' was built under R version 3.4.4 

Attaching package: 'dplyr'

The following objects are masked from 'package:data.table':

    between, first, last

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Error in sample(Test_x$RowNames_x) : object 'Test_x' not found
Execution halted
Loading required package: methods
Warning message:
package 'miniUI' was built under R version 3.4.4 
Warning message:
package 'data.table' was built under R version 3.4.4 

Attaching package: 'dplyr'

The following objects are masked from 'package:data.table':

    between, first, last

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Error in sample(Test_x$RowNames_x) : object 'Test_x' not found
Execution halted
Loading required package: methods
Warning message:
package 'miniUI' was built under R version 3.4.4 
Warning message:
package 'data.table' was built under R version 3.4.4 

Attaching package: 'dplyr'

The following objects are masked from 'package:data.table':

    between, first, last

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


| Hi! I see that you have some variables saved in your workspace. To keep
| things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type
| rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.

Warning message:
package 'swirl' was built under R version 3.4.4 
Error in paste0(dir, "MAIN.csv") : 
  cannot coerce type 'closure' to vector of type 'character'
Calls: readLines -> paste0
Execution halted
Loading required package: methods
Warning message:
package 'miniUI' was built under R version 3.4.4 
Warning message:
package 'data.table' was built under R version 3.4.4 

Attaching package: 'dplyr'

The following objects are masked from 'package:data.table':

    between, first, last

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


| Hi! I see that you have some variables saved in your workspace. To keep
| things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type
| rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.

Warning message:
package 'swirl' was built under R version 3.4.4 

Attaching package: 'testthat'

The following object is masked from 'package:swirl':

    skip

The following object is masked from 'package:dplyr':

    matches

Warning message:
package 'testthat' was built under R version 3.4.4 
Warning message:
package 'knitr' was built under R version 3.4.4 
Error in sample(Test_x$RowNames_x) : object 'Test_x' not found
Execution halted
Loading required package: methods
Warning message:
package 'miniUI' was built under R version 3.4.4 
Warning message:
package 'data.table' was built under R version 3.4.4 

Attaching package: 'dplyr'

The following objects are masked from 'package:data.table':

    between, first, last

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


| Hi! I see that you have some variables saved in your workspace. To keep
| things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type
| rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.

Warning message:
package 'swirl' was built under R version 3.4.4 

Attaching package: 'testthat'

The following object is masked from 'package:swirl':

    skip

The following object is masked from 'package:dplyr':

    matches

Warning message:
package 'testthat' was built under R version 3.4.4 
Warning message:
package 'knitr' was built under R version 3.4.4 
Error in sample(Test_x$RowNames_x) : object 'Test_x' not found
Execution halted
Loading required package: methods
Warning message:
package 'miniUI' was built under R version 3.4.4 
Warning message:
package 'data.table' was built under R version 3.4.4 

Attaching package: 'dplyr'

The following objects are masked from 'package:data.table':

    between, first, last

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


| Hi! I see that you have some variables saved in your workspace. To keep
| things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type
| rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.

Warning message:
package 'swirl' was built under R version 3.4.4 

Attaching package: 'testthat'

The following object is masked from 'package:swirl':

    skip

The following object is masked from 'package:dplyr':

    matches

Warning message:
package 'testthat' was built under R version 3.4.4 
Warning message:
package 'knitr' was built under R version 3.4.4 
Error in sample(Test_x$RowNames_x) : object 'Test_x' not found
Execution halted
Loading required package: methods
Warning message:
package 'miniUI' was built under R version 3.4.4 
Warning message:
package 'data.table' was built under R version 3.4.4 

Attaching package: 'dplyr'

The following objects are masked from 'package:data.table':

    between, first, last

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


| Hi! I see that you have some variables saved in your workspace. To keep
| things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type
| rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.

Warning message:
package 'swirl' was built under R version 3.4.4 

Attaching package: 'testthat'

The following object is masked from 'package:swirl':

    skip

The following object is masked from 'package:dplyr':

    matches

Warning message:
package 'testthat' was built under R version 3.4.4 
Warning message:
package 'knitr' was built under R version 3.4.4 
Error in sample(Test_x$RowNames_x) : object 'Test_x' not found
Execution halted

**Comment by jwijffels** [comment]
well that means your code has run :)
ONCE means, run the code once and put the code into the log which you saw there.

**Comment by AlexKost5791** [comment]
I do not think it was successful even once. It's supposed to create "matched.data.main" CSV file and save with time stamp 09:55
Nothing happened.
Do I have to do something with Text_x.csv file ?
________________________
Start_time <- Sys.time()
# Test_x <- read.csv("C:/Users/akostyns/Documents/R Studio/Excel for R/Today only/Test_x.csv")
# MAIN <- read.csv("C:/Users/akostyns/Documents/R Studio/Excel for R/Today only/MAIN.csv")

library("shiny", lib.loc="C:/R-3.4.3/library")
library("miniUI", lib.loc="C:/R-3.4.3/library")
library("data.table", lib.loc="C:/R-3.4.3/library")
library("dplyr", lib.loc="C:/R-3.4.3/library")
library("tidyr", lib.loc="C:/R-3.4.3/library")
library("swirl", lib.loc="C:/R-3.4.3/library")
library("testthat", lib.loc="C:/R-3.4.3/library")
library("knitr", lib.loc="C:/R-3.4.3/library")

for(x in 1:5){
Test_x$RowNames_x <- sample(Test_x$RowNames_x)
Test_x$RowNames <- sample(Test_x$RowNames)
print(head(Test_x))
Test_x[3] <- ifelse(Test_x$RowNames_x==Test_x$RowNames,1,0)
filter.data <- filter(Test_x,Test_x$Summary_x==1)
if(nrow(filter.data) ==0){
  {""}
  }else{ 
  print(filter.data)

filter.data.interim <- filter.data
filter.data.interim[4] <- Sys.time()
names(filter.data.interim)[4] <- "TimeStamp"
filter.data.main <- filter.data.interim
filter.data.main <- rbind(filter.data.interim,filter.data.main)}}
End_time <- Sys.time()
time_check <- format(Sys.time(),"%d_%m_%Y  %H_%M_%S %p")
print(End_time-Start_time)
matched.data.main <- data.frame(filter.data.main[,c("RowNames","TimeStamp")])
matched.data.main <-left_join(matched.data.main,MAIN,by="RowNames")
matched.data.main <- unique(matched.data.main)
dir <- "C:/Users/akostyns/Documents/R Studio/Excel for R/Today only/"
write.csv(matched.data.main,paste(dir,"Matched.Data_",time_check,".csv",sep = ""),row.names = FALSE)

**Comment by jwijffels** [comment]
Your code failed at  `Error in sample(Test_x$RowNames_x) : object 'Test_x' not found`
The schedule run but your code is buggy.
You need to fix your R code. Mark that such a script starts from a blank sessions, Don't assume you have objects available for use if you don't create them in your code.

**Comment by AlexKost5791** [comment]
Thanks, Jan.  I will try.

**Comment by AlexKost5791** [comment]
But if I run my code independently from task scheduler it runs really fast -Time difference of 2.633089 secs

**Comment by AlexKost5791** [comment]
Results after your comment:

RowNames | TimeStamp | Numbers
-- | -- | --
5348772 | 4/12/2018 14:38 | 7_22_29_35_39_42

**Comment by jwijffels** [comment]
Put `options(echo = TRUE)` at the start of the script which you want to schedule. Schedule it e.g. ONCE and see to the log and if it fails, you'll see where it fails and where you'll need to fix your R code.

**Comment by AlexKost5791** [comment]
Ok, will try.

**Comment by AlexKost5791** [comment]
I 've inserted options(echo = TRUE) as you recommended:

Log tail says:
```
____
Start_time <- Sys.time()
> 
> # Test_x <- read.csv("C:/Users/akostyns/Documents/R Studio/Excel for R/Today only/Test_x.csv")
> # MAIN <- read.csv("C:/Users/akostyns/Documents/R Studio/Excel for R/Today only/MAIN.csv")
> library("shiny", lib.loc="C:/R-3.4.3/library")
Loading required package: methods
> library("miniUI", lib.loc="C:/R-3.4.3/library")
Warning message:
package 'miniUI' was built under R version 3.4.4 
> library("data.table", lib.loc="C:/R-3.4.3/library")
Warning message:
package 'data.table' was built under R version 3.4.4 
> library("dplyr", lib.loc="C:/R-3.4.3/library")

Attaching package: 'dplyr'

The following objects are masked from 'package:data.table':

    between, first, last

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

> library("tidyr", lib.loc="C:/R-3.4.3/library")
> library("swirl", lib.loc="C:/R-3.4.3/library")

| Hi! I see that you have some variables saved in your workspace. To keep
| things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type
| rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.

Warning message:
package 'swirl' was built under R version 3.4.4 
> library("testthat", lib.loc="C:/R-3.4.3/library")

Attaching package: 'testthat'

The following object is masked from 'package:swirl':

    skip

The following object is masked from 'package:dplyr':

    matches

Warning message:
package 'testthat' was built under R version 3.4.4 
> library("knitr", lib.loc="C:/R-3.4.3/library")
Warning message:
package 'knitr' was built under R version 3.4.4 
> for(x in 1:1){
+ Test_x$RowNames_x <- sample(Test_x$RowNames_x)
+ Test_x$RowNames <- sample(Test_x$RowNames)
+ print(head(Test_x))
+ Test_x[3] <- ifelse(Test_x$RowNames_x==Test_x$RowNames,1,0)
+ filter.data <- filter(Test_x,Test_x$Summary_x==1)
+ if(nrow(filter.data) ==0){
+   {""}
+   }else{ 
+   print(filter.data)
+ filter.data.interim <- filter.data
+ filter.data.interim[4] <- Sys.time()
+ names(filter.data.interim)[4] <- "TimeStamp"
+ filter.data.main <- rbind(filter.data.interim,filter.data.main)}}
Error in sample(Test_x$RowNames_x) : object 'Test_x' not found
Execution halted
```

**Comment by AlexKost5791** [comment]
Does it mean that I have to work on creating object for  'Test_x' ?

**Comment by jwijffels** [comment]
Please read your code, you commented out `# Test_x <- read.csv("C:/Users/akostyns/Documents/R Studio/Excel for R/Today only/Test_x.csv")` no wonder it complains later on that `object 'Test_x' not found`

**Comment by AlexKost5791** [comment]
Got it. Now it's without # sign, meaning un commented. This time I ran and black pop up window was holding 2 minutes or so.

And you were right ...
__
Warning message:
package 'knitr' was built under R version 3.4.4 
> for(x in 1:1){
+ Test_x$RowNames_x <- sample(Test_x$RowNames_x)
+ Test_x$RowNames <- sample(Test_x$RowNames)
+ print(head(Test_x))
+ Test_x[3] <- ifelse(Test_x$RowNames_x==Test_x$RowNames,1,0)
+ filter.data <- filter(Test_x,Test_x$Summary_x==1)
+ if(nrow(filter.data) ==0){
+   {""}
+   }else{ 
+   print(filter.data)
+ filter.data.interim <- filter.data
+ filter.data.interim[4] <- Sys.time()
+ names(filter.data.interim)[4] <- "TimeStamp"
+ filter.data.main <- rbind(filter.data.interim,filter.data.main)}}
  RowNames_x RowNames Summary_x
1    1848194  7883340         0
2    5434008  3155176         0
3    7901577  3206859         0
4    1650662  4120015         0
5    3619603   532366         0
6    2473680  1512756         0
  RowNames_x RowNames Summary_x
1    1373705  1373705         1
Error in rbind(filter.data.interim, filter.data.main) : 
  object 'filter.data.main' not found
Execution halted

**Comment by AlexKost5791** [comment]
It's my code messing up, will fix it soon by adding filter.data.main.csv and pulling it first

**Comment by AlexKost5791** [comment]
Bingo!!! Thank you very much Ian! Very helpful. You are absolutely great.
Best regards, Alex
