### ISSUE TITLE
Allow arbitrary schedules

### ISSUE THREAD

**Issue by condwanaland** [jwijffels/taskscheduleR#39]
Would it be possible to allow for more flexible schedules in the Rstudio addin? Specifically I would find yearly and quarterly schedules useful, but the ability to set arbitrary ones could also come in handy.

**Comment by jwijffels** [comment]
It's not clear to me what you mean with arbitrary schedules. The R package interfaces to schtasks.exe and allows to set any arbitrary schedule allowed by schtasks.exe as defined at https://github.com/bnosac/taskscheduleR/blob/master/inst/docs/schtasks.pdf

**Comment by jwijffels** [comment]
Closing as no active feedback given in last month.
