### ISSUE TITLE
Running the examples

### ISSUE THREAD

**Issue by Patrikios** [jwijffels/taskscheduleR#4]
The installation from the alternative source was successful however the package doesn't work for me. 

I try to run, in order to test it, the example R file Hello World::

myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")

taskscheduler_create(taskname = "myfancyscript", rscript = myscript, 
                 schedule = "ONCE", starttime = format(Sys.time() + 62, "%H:%M"))
In 62 secs goes on a black window up and in a sec disappears. That's it the codes messages do not appear in the console.

in addition:

> tasks <- taskscheduler_ls()
> Error in $<-.data.frame(_tmp_, "TaskName", value = character(0)) : 
> replacement has 0 rows, data has 149
> 
> str(tasks)
> Error in str(tasks) : object 'tasks' not found

I also created my own script that writes a .csv, doesn`t work neither. Is there something that I neglected in the code or in the settings?

**Comment by jwijffels** [comment]
It appears to have run. Can you look at the log. Which can be found at system.file("extdata", "helloworld.log", package = "taskscheduleR")

Regarding taskscheduler_ls() can you show me the output of str below. Can you also provide the windows version?

```
cmd <- sprintf('schtasks /Query /FO CSV /V')
x <- system(cmd, intern = TRUE)
f <- tempfile()
writeLines(x, f)
x <- data.table::fread(f)
x <- data.table::setDF(x)

str(x)
```

**Comment by Patrikios** [comment]
no log file created

    str(x)

gives me

'data.frame':	149 obs. of  28 variables:
 $ N„chste Laufzeit                                           : chr  "18.03.2016 17:30:00" "18.03.2016 17:24:00" "18.03.2016 17:10:00" "19.03.2016 08:38:00" ...
 $ Status                                                     : chr  "Bereit" "Bereit" "Bereit" "Bereit" ...
 $ Letztes Ergebnis                                           : chr  "0" "0" "0" "0" ...
 $ Autor                                                      : chr  "Adobe Systems Incorporated"  
 $ Auszufhrende Aufgabe                                      : chr  "C:\\Windows\\SysWOW64\\Macromed\\Flash\\FlashPlayerUpdateService.exe " "C:\\Program Files (x86)\\Citrix\\GoToMeeting\\4628\\g2mupdate.exe " "C:\\Program Files (x86)\\Citrix\\GoToMeeting\\4628\\g2mupload.exe " "C:\\Program Files (x86)\\Google\\Update\\GoogleUpdate.exe /c" ...
 $ Starten in                                                 : chr  "Nicht zutreffend" "C:\\Program Files (x86)\\Citrix\\GoToMeeting\\4628" "C:\\Program Files (x86)\\Citrix\\GoToMeeting\\4628" "Nicht zutreffend" ...
 $ Kommentar                                                  : chr  "Mit diesem Task ist Ihre Flash Player-Installation immer aktuell und verwendet die neuesten Verbesserungen und Sicherheits-Fixe"| __truncated__ "Keeps GoToMeeting up to date. This task is removed when GoToMeeting is uninstalled." "Uploads diagnostic info previously recorded by GoToMeeting with your consent. This task is removed when GoToMeeting is uninstal"| __truncated__ "H„lt Ihre Google-Software auf dem neuesten Stand. Falls diese Anwendung deaktiviert oder angehalten wird, wird Ihre Google-Soft"| __truncated__ ...
 $ Status der geplanten Aufgabe                               : chr  "Aktiviert" "Aktiviert" "Aktiviert" "Aktiviert" ...
 $ Leerlaufzeit                                               : chr  "Deaktiviert" "Deaktiviert" "Deaktiviert" "Deaktiviert" ...
 $ Energieverwaltung                                          : chr  "Bei Batteriebetrieb beenden" "" "" "" ...
 $ Aufgabe l”schen, falls nicht verlegt                       : chr  "Aktiviert" "Aktiviert" "Aktiviert" "Aktiviert" ...
 $ Aufgabe beenden, falls sie X St. und X Min. ausgefhrt wird: chr  "72:00:00" "72:00:00" "72:00:00" "Deaktiviert" ...
 $ Zeitplan                                                   : chr  "Zeitplaninformationen sind in diesem Format nicht verfgbar." "Zeitplaninformationen sind in diesem Format nicht verfgbar." "Zeitplaninformationen sind in diesem Format nicht verfgbar." "Zeitplaninformationen sind in diesem Format nicht verfgbar." ...
 $ Zeitplantyp                                                : chr  "T„glich " "T„glich " "T„glich " "Bei der Anmeldung" ...
 $ Startzeit                                                  : chr  "01:30:00" "09:24:00" "09:10:00" "Nicht zutreffend" ...
 $ Startdatum                                                 : chr  "01.01.2000" "15.03.2016" "15.03.2016" "Nicht zutreffend" ...
 $ Enddatum                                                   : chr  "Nicht zutreffend" "Nicht zutreffend" "Nicht zutreffend" "Nicht zutreffend" ...
 $ Tage                                                       : chr  "Alle 1 Tag(e)" "Alle 1 Tag(e)" "Alle 1 Tag(e)" "Nicht zutreffend" ...
 $ Monate                                                     : chr  "Nicht zutreffend" "Nicht zutreffend" "Nicht zutreffend" "Nicht zutreffend" ...
 $ Wiederholung: Jede(n)                                      : chr  "1 Stunde(n), 0 Minute(n)" "1 Stunde(n), 0 Minute(n)" "2 Stunde(n), 0 Minute(n)" "Nicht zutreffend" ...
 $ Wiederholung: Bis: Zeit                                    : chr  "Keine" "Keine" "Keine" "Nicht zutreffend" ...
 $ Wiederholung: Bis: Dauer                                   : chr  "24 Stunde(n), 0 Minute(n)" "23 Stunde(n), 59 Minute(n)" "23 Stunde(n), 59 Minute(n)" "Nicht zutreffend" ...
 $ Wiederholung: Beenden, falls immer noch ausgefhrt         : chr  "Deaktiviert" "Deaktiviert" "Deaktiviert" "Nicht zutreffend" ...

**Comment by jwijffels** [comment]
Ok. Apparently HostName and Taskname are not in you taskscheduler_ls which is competely in German. 

What information did gave you?

```
myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")
taskscheduler_create(taskname = "myfancyscript", rscript = myscript, schedule = "ONCE", starttime = format(Sys.time() + 62, "%H:%M"))
```

What is your R_HOME?

```
Sys.getenv("R_HOME")
```

Where is Rscript? Is it at 

```
file.path(Sys.getenv("R_HOME"), "bin", "Rscript.exe")
```

And what windows system is it you are running on and what rights do you have on that system?

**Comment by Patrikios** [comment]
```
> myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")
> taskscheduler_create(taskname = "myfancyscript", rscript = myscript, schedule = "ONCE",     starttime = format(Sys.time() + 62, "%H:%M"))
[1] "ERFOLGREICH: Die geplante Aufgabe \"myfancyscript\" wurde erfolgreich erstellt."
```

...saying that it was successfully scheduled

```
Sys.getenv("R_HOME")
[1] "C:/PROGRA~1/R/R-32~1.4"

file.path(Sys.getenv("R_HOME"), "bin", "Rscript.exe")
[1] "C:/PROGRA~1/R/R-32~1.4/bin/Rscript.exe"
```

Version windows 7 profesional, user rights

**Comment by jwijffels** [comment]
So it clearly indicates that the script was scheduled. What does

`list.files(system.file("extdata", package = "taskscheduleR"))`

give you and

`cat(readLines(system.file("extdata", "helloworld.log", package = "taskscheduleR")))`

**Comment by Patrikios** [comment]
```
> list.files(system.file("extdata", package = "taskscheduleR"))
[1] "a.R"          "helloworld.R"

> cat(readLines(system.file("extdata", "helloworld.log", package = "taskscheduleR")))
Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former
```

**Comment by jwijffels** [comment]
Right and

`system.file("extdata", package = "taskscheduleR")`

**Comment by Patrikios** [comment]
```
> system.file("extdata", package = "taskscheduleR")
[1] "C:/Program Files/R/R-3.2.4/library/taskscheduleR/extdata"
```

**Comment by jwijffels** [comment]
Ok get it. Install the package again (I just uploaded a new version) so that taskscheduler_ls will work for your setting (apparently with German column names)

`install.packages("taskscheduleR", repos = "http://www.datatailor.be/rcube", type = "source")`

Copy-paste the helloworld.R file to a location **without** spaces. And rerun taskscheduler_create again.

**Comment by Patrikios** [comment]
removed and installed the package anew.
I scheduled the task anew as well, however not working still.
Black window goes of and that`s it, no log file created.

**Comment by jwijffels** [comment]
Can you repeat that again:
`install.packages("taskscheduleR", repos = "http://www.datatailor.be/rcube", type = "source")`
I've added a check to 100% make sure there are no spaces in your path

**Comment by Patrikios** [comment]
Thank u for ur help im away now from the pc i will need to check later i will let u know

**Comment by OliverBLMS** [comment]
I can confirm that the latest version work with current system settings. by adding `try`  in `taskscheduler_ls()` this function does not throw an error anymore.

**Comment by jwijffels** [comment]
Thanks for the feedback, closing this issue as solved.

**Comment by Patrikios** [comment]
Hi,
sorry for later feedback. 
I tried again. The problem was correctly foreseen by you that in the directory description should not be present any spaces. 

```
  Error in taskscheduler_create(taskname = "myfancyscript", rscript = myscript,  : 
  Full path to filename 'C:/Program Files/R/R-3.2.4/library/taskscheduleR/extdata/helloworld.R' 
  contains spaces, put your script in another location which contains no spaces
```

As I got R in my Programm File 'C:/Program Files/R/R-3.2.4' the script scheduling did not work. Placing the helloworld Script to another location path without spaces is easy. What I do not have the knowledge to do is to replicate 

```
  myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")
```

from within the changed directory. I would appreciate if you could point out to me how to do read in a script as object/value in the global R environment.

**Comment by jwijffels** [comment]
change myscript with
`myscript <- 'C:\\locationfolder\\where\\you\\put\\helloworld.R"
`and run 
`taskscheduler_create(taskname = "myfancyscript", rscript = myscript, schedule = "ONCE", starttime = format(Sys.time() + 62, "%H:%M"))`

**Comment by Patrikios** [comment]
Straight forward, now working. Thank you for the package!
