### ISSUE TITLE
Run whether user is logged on or not

### ISSUE THREAD

**Issue by ibombonato** [jwijffels/taskscheduleR#44]
The default setting is that the task will only run when user is logged in. Is there a way to change this setting to allow tasks to run whether user is logged on or not?

![image](https://user-images.githubusercontent.com/1737342/39665519-1ed940a8-506c-11e8-8293-3d324370c581.png)

**Comment by jwijffels** [comment]
Haven't tried this but I think what you need is to pass in the argument 
`schtasks_extra = "/IT"` in `taskscheduler_create`
See the documentation of schtasks.exe /Create /? if you run it in a shell.

**Comment by jwijffels** [comment]
I presume this worked for you, if not feel free to reopen.

**Comment by ibombonato** [comment]
Hi, sorry about the delay, but it does not work with the argument `schtasks_extra = "/IT"`.

It worked when I passed the user and password:

`schtasks_extra = "/ru username /rp password`

**Comment by jwijffels** [comment]
Good to know!

**Comment by rluech** [comment]
Hi again. I continue to have issues with the Windows taskscheduler. I'm not sure if this is the right place to put the question but I don't know where else...

I need to run my tasks independent if the user is logged in or not. Neither `schtasks_extra = "/IT"`  nor `schtasks_extra = "/ru username /rp password` helped, so I simply adjusted the task manually via taskschd GUI. Now the tasks run even if the user is logged off. But this had an unexpected sideffect. Now my scripts no longer connect to remote drives (e.g. `I\:` and `P\`:, but still can connect to local drive `dir(C:\...)` as well as to FTP server `getURL(ftp://...)`).  Interactively I get all connections. Of course, I did not check the checkbox for _"Do not store password. The task will only have access to local resources"_, compare printscreen above. I run the task with _"Run with highest privilages"_. But actually I have tried all possible combinations of these checkboxes. Running on Windows 10 as user with admin rights.

Any Idea? Or hint where to get help? Taskschd seems a blackbox to me.

**Comment by jwijffels** [comment]
That's just because you run the script now as the admin user and no longer as your own user. If the admin user does not have all driver I\: P:\ mounted, they will not be available. So this means you need to set up your admin user to have these drives mounted and also of course all R packages should be the same as your own user if you want to be 100% sure the same is execute.

**Comment by rluech** [comment]
Hm. I think I understand. Set up the admin the same as my user makes things complicated. I now setup Windows to never log off my user. There sems to be the option to run taskschd as SYSTEM, is this a solution? What's the difference from System to a user or admin?

**Comment by jwijffels** [comment]
https://support.microsoft.com/en-us/help/120929/how-the-system-account-is-used-in-windows

**Comment by MislavSag** [comment]
I have tried with following code:
```
taskscheduler_create(taskname = "stock_forensis_task", rscript = "C:/R_code/stock_forensis_updates.R",
                     schedule = "DAILY", starttime = "15:30", startdate = format(Sys.Date() + 1, "%d/%m/%Y"),
                     schtasks_extra = '/RU "CT-VM-01\\msagovac" /RP "pass"')
```
but it doesn't work when I am logged off. It works if when I am looged in.
I tried it on azure VM.

Do you know what can be the reason?

**Comment by jwijffels** [comment]
Maybe quote username and pwd differently

**Comment by MislavSag** [comment]
How differently? I tried with and without computer name: 
```
'/RU "CT-VM-01\\msagovac" /RP "pass"'
'/RU "CT-VM-01/msagovac" /RP "pass"'
'/RU "msagovac" /RP "pass"'
```
but non of this work.

**Comment by jwijffels** [comment]
maybe '/RU msagovac /RP pass'

**Comment by JiaxiangBU** [comment]
> maybe '/RU msagovac /RP pass'

It works for me. 

I use `/RU CORP\\lijiaxiang /RP  ******` and successfully run the script both in the logging in or out.

**Comment by conmaster2112** [comment]
My program runs programs but they are not Visible.
Why?

**Comment by arun7pulse** [comment]
I am looking for a solution to this problem in the cmd line.

**Comment by thekumarakshay** [comment]
Hi guys,
Can anyone help me how to set the checkbox of 'Run whether the user is logged on or not' to true via command prompt and that too without the password as I don't have access to user logged in password as the org uses single sign on.

**Comment by dchiu911** [comment]
I tried `/RU username /RP password`  but got this:
```
WARNING: The task is registered, but may fail to start. Batch logon privilege needs to be enabled for the task principal.\r"
```
I am also unable to edit local security policy because my user account does not have admin privileges under organizational policies. Does this mean I am unable to schedule any tasks unless I am logged on?
