### ISSUE TITLE
RStudio-AddIn...

### ISSUE THREAD

**Issue by herrmannrobert** [jwijffels/taskscheduleR#46]
How can I schedule tasks every 5 minutes by using the RStudio-AddIn, i.e., equivalent to the example given in e.g. reference manual:

`## Run every 5 minutes, starting from 10:40taskscheduler_create(taskname = "myfancyscript_5min", rscript = myscript,schedule = "MINUTE", starttime = "10:40", modifier = 5)`

Thanks in advance...

**Comment by jwijffels** [comment]
You can't, the modifier argument is not put into the RStudio addin. Just use the R code instead as shown in the readme.

**Comment by herrmannrobert** [comment]
Got it - thanks for the quick response...
