### ISSUE TITLE
script works ONCE but not DAILY (status 16389)

### ISSUE THREAD

**Issue by Tazinho** [jwijffels/taskscheduleR#49]
Hi, thanks for this great package!

I am using the addin and when I run my script once, everything works fine with locale "%Y-%m-%d".
However, when I delete the old task and set up a new one with Schedule DAILY I get the additional status 16389 message and no script is sent to the task folder.

Would appreciate any help on this!

**Comment by jwijffels** [comment]
Read the last part of the readme.

**Comment by Tazinho** [comment]
It worked for me from the console :)

Regarding the add-in:
I did everything as stated in the readme (run as admin; delete old task; procedure that worked for ONCE). If you have a specific advice, pls let me know. Otherwise it's also fine of course. I am just asking, since I would prefer to use the add-in.

**Comment by jwijffels** [comment]
Probably you did not fill in the correct data format of your locale in the add-in.

**Comment by datasurfermtv** [comment]
Here's what i ended up doing:

OPTION 1 (Preferred Method):
Additional arguments to RScript:
startdate = format(Sys.Date()+1, "%m/%d/%Y")

Change Date format of your locale:
%m/%d/%Y
(note this is the way your machine's clock is formatted!)

OPTION 2 (The dirty method)
Create the scheduled task for once and then open Windows Task Scheduler. (It's an app on installed on your computer). You can open it and change the time and frequency of the task.
