### ISSUE TITLE
Issues in Changing Code

### ISSUE THREAD

**Issue by aheissmetrica** [jwijffels/taskscheduleR#50]
I am trying to use taskscheuleR (the add-in for Rstudio), but the code I am trying to schedule needs to be changed and updated daily or weekly. Right now I can't seem to start a task and update the code at a later time, saving it with the same name in the same place, and have the task run with the new updated code. Is there any way around that or is that just what it will do or am I missing something? Any help would be great.

**Comment by jwijffels** [comment]
You can not have 2 schedules with the same identifier, delete the schedule and reschedule it with your new code
