### ISSUE TITLE
Install package "taskscheduleR"

### ISSUE THREAD

**Issue by arti1996** [jwijffels/taskscheduleR#51]
I try to execute installation commands, but it isn't work.

I have a one Error: "installation of package ‘taskscheduleR’ had non-zero exit status". Then, I can't invoke library.

> install.packages("taskscheduleR", repos = "http://www.datatailor.be/rcube", type = "source")
Warning: dependency ‘data.table’ is not available
trying URL 'http://www.datatailor.be/rcube/src/contrib/taskscheduleR_1.0.tar.gz'
Content type 'application/x-gzip' length 146885 bytes (143 KB)
downloaded 143 KB

ERROR: dependency 'data.table' is not available for package 'taskscheduleR'
* removing 'C:/Users/Datatekin/Documents/R/R-3.5.1/library/taskscheduleR'
In R CMD INSTALL

The downloaded source packages are in
        ‘C:\Users\USER\AppData\Local\Temp\Rtmpk3LSz1\downloaded_packages’
Warning message:
In install.packages("taskscheduleR", repos = "http://www.datatailor.be/rcube",  :
  installation of package ‘taskscheduleR’ had non-zero exit status
> library(taskscheduleR)
Error in library(taskscheduleR) : 
  there is no package called ‘taskscheduleR’

**Comment by arti1996** [comment]
And others ways, don't work, so the URL for datatailor is old?

**Comment by jwijffels** [comment]
The readme says the following shown below, that's apparently not what you did as the error message you have indicates that `ERROR: dependency 'data.table' is not available for package 'taskscheduleR'`



```
install.packages('data.table')
install.packages('knitr')
install.packages("taskscheduleR", repos = "http://www.datatailor.be/rcube", type = "source")
```
