### ISSUE TITLE
Error in observeEventHandler

### ISSUE THREAD

**Issue by Ivanaz916** [jwijffels/taskscheduleR#53]
I return the  below error when trying to run my task via rstudio plug-in.  If I move extdata, what do I need to also run in R so the task scheduler can properly work?

Error in observeEventHandler: Make sure the RscriptRepository does not contain spaces, change argument 

C:/Users/xx xx/Documents/R/win-library/3.4/taskscheduleR/extdata to another location on your drive which contains no spaces

**Comment by jwijffels** [comment]
Change the Rscript repo in the Rstudio plugin and put in that field the path to a folder where you have access to and which contains no spaces.

**Comment by Ivanaz916** [comment]
Hi Jan, I tried your solution - the R script I'm trying to schedule is saved in: C:/shiny_task_scheduler/my_script.R.

I still return the error I originally posted( also re-copied below).   Is it possible I need to change the location of where taskscheuleR is installed?  Also I am using taskscheduleR with the R Studio plugin - perhaps if I switch to running it directly in R as shown in your Cran-R post? (https://cran.r-project.org/web/packages/taskscheduleR/vignettes/taskscheduleR.html)

"Warning: Error in observeEventHandler: Make sure the RscriptRepository does not contain spaces, change argument C:/Users/Ivana Zgaljic/Documents/R/win-library/3.4/taskscheduleR/extdata to another location on your drive which contains no spaces"

**Comment by jwijffels** [comment]
In the UI, change the location to C:/shiny_task_scheduler and select the file from another location. Your my_script.R will then be copy-pasted to C:/shiny_task_scheduler
![capture](https://user-images.githubusercontent.com/1710810/45361808-6c082480-b5d3-11e8-99e2-046b7ff0b590.PNG)
