### ISSUE TITLE
Not an issue - just a question

### ISSUE THREAD

**Issue by UTexas80** [jwijffels/taskscheduleR#55]
I am relative newcomer to R. Can you please help me understand whether it is possible to schedule a .rmd markdown file to run in task scheduler. I am looking to automate report generation and this would be a great feature.

Thank you.

**Comment by jwijffels** [comment]
write a script which contains something like rmarkdown::run("path/to/your/rmd/file") and schedule that with with this package on whichever timepoint you like. Please ask further questions like this on stackoverflow.
