### ISSUE TITLE
Taskscheduler availibility for R versions

### ISSUE THREAD

**Issue by hammadhassan90** [jwijffels/taskscheduleR#56]
Hello. Thank you very much for creating this package. I am trying to install it but I keep getting the error:
 package ‘taskscheduleR’ is not available (for R version 3.3.2)
Can you tell me the correct version of R I need to have for it to be able to install and work.

**Comment by jwijffels** [comment]
The taskscheduleR R package does not depend on any version of R. You can install it on any version of R.
I presume you tried to install the package from CRAN? Apparently CRAN has not built a binary for R version 3.3.2.
Just install it then as follows `install.packages('taskscheduleR', type = 'source')`
