### ISSUE TITLE
Add Packrat Support

### ISSUE THREAD

**Issue by jtelleria** [jwijffels/taskscheduleR#57]
Could Packrat Support be added to taskscheduleR  Package?

Or at least: How could I configure taskscheduleR with Packrat? Is there any way to schedule not a Script but an Rstudio Project?

http://rstudio.github.io/packrat/

Thank you.
Best,
Juan

**Comment by jwijffels** [comment]
There are no plans to add packrat support. If you want to use specific packages or specific versions in your script. Learn what happens at R Startup. Look to ?Startup and make sure you set the right environment System-wide and user-wide environment variables and if needed, point your libpath to whichever folder you have where the packages are.
