### ISSUE TITLE
 Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'miniUI-0.1.1.1'; `directoryPath` = ''

### ISSUE THREAD

**Issue by bpffjl** [jwijffels/taskscheduleR#64]
I'm getting this error when I try to open the taskscheduleR add-in. I've tried to reinstall miniUI, but that didn't solve it. Any thoughts?

**Comment by jwijffels** [comment]
What is the path that you use in the Rscript repo section of the add-in? My first thought would be that you need to put your R packages in a standard location. As in not on a shared drive.

**Comment by bpffjl** [comment]
Thanks! I seem to have packages being saved to a network drive and into program files. taskscheduleR was saved into the network drive. Thanks might be the issue.

**Comment by jwijffels** [comment]
Yes, put them at a non-network folder. As in C:/Users/Youruser/Documents/R/win-library/3.5
