### ISSUE TITLE
Not sure if I am getting the correct output

### ISSUE THREAD

**Issue by seekerknow** [jwijffels/taskscheduleR#69]
Hi,

Just trying to follow the steps in the your READ.ME but not getting past 'Listening on http://127.0.0.1:4165.

I am using taskscheduleR via the add-in, have admin rights to the computer, run RStudio as an admin, and have specified the path to my desktop. Surely I am missing something but can't seem to work it out!

Also, hopefully not duplicating any issue, I am largely interesting in writing a csv (write.csv) function as the end outcome from this task, which will later be consumed by another system so hoping that this package does exactly that?

Thanks,
Seeker

![image](https://user-images.githubusercontent.com/49753508/58771233-6a194200-85f6-11e9-963d-c024e0b61069.png)

**Comment by jwijffels** [comment]
What is the issue you are reporting?
