### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by OliverBLMS** [jwijffels/taskscheduleR#7]
Is it only at my screen that the layout is kinda choppy:
![image](https://cloud.githubusercontent.com/assets/4517850/14044665/6a263d42-f293-11e5-89f6-64a0f14ba18b.png)

**Comment by jwijffels** [comment]
Yes :)
Feel free to change the shiny code for a pull request. 
I was probably due to adding the rscript repo.

**Comment by OliverBLMS** [comment]
Hmm weird; Just did a fresh install of the package and the UI is still like in the picture. Any idea's? 
I'm trying to adjust the height of the dialogviewer, but it doenst react to the adjustments.

**Comment by jwijffels** [comment]
probably its related to the scrollbar which I don't get 
i'm getting the one shown at https://github.com/jwijffels/taskscheduleR/blob/master/inst/img/taskscheduleR-rstudioaddin.png
maybe increase the height?

**Comment by OliverBLMS** [comment]
back on this. seems like this is a resolution problem when switching rstudio between screens with different resolution. 
on my monitor it show the addin perfectly. but on my laptop screen it tries to adjust the addin.

![image](https://cloud.githubusercontent.com/assets/4517850/14241651/c96efc06-fa4c-11e5-8408-6f35a873c086.png)

![image](https://cloud.githubusercontent.com/assets/4517850/14241656/d46f2d24-fa4c-11e5-8668-73971bbe139e.png)
