### ISSUE TITLE
Not able to Schedule r script with the help of taskscheduleR package 

### ISSUE THREAD

**Issue by sumedhkumarprasad** [jwijffels/taskscheduleR#71]
![image](https://user-images.githubusercontent.com/29379271/73446059-15df8100-4382-11ea-8cae-e7deeacd6395.png)

This is my R script:

library(taskscheduleR)
library(shiny)
library(miniUI)
myscript<- "C:/Users/Desktop/R alert folder/Alert_Code.R"
 myscript <-system.file("extdata", 
                     "Alert_Code.R",
                      package = "taskscheduleR")
#  run script once within 62 seconds
taskscheduler_create(taskname = "myfancyscript_5min", rscript = myscript,
                     schedule = "MINUTE", 
                     starttime = format(Sys.time(),"%H:%M"),
                     modifier = 1)

Please help me in resolve this error. Thanks in advanced.

**Comment by jwijffels** [comment]
Things you should check
1. Does your R script exist. As in `file.exists(myscript)` should give you TRUE
2. Consider using the `startdate `argument of taskscheduler_create (scheduling something at 9/2/2018 means something different than 2/9/2018 depending on your locale)
