### ISSUE TITLE
Scheduled run is not importing from external file

### ISSUE THREAD

**Issue by jarichardsonccbf** [jwijffels/taskscheduleR#73]
I am using the Rstudio addin to set this up. I set the Rscript repo to the location of the script and the external file. In the log I see:

```
Error: `path` does not exist: 'CO2 Report 2-25-20.xlsx'
```

But the file is right there and loads in when running the script in Rstudio. Any advice?

**Comment by jwijffels** [comment]
Same question as https://github.com/bnosac/taskscheduleR/issues/60
