### ISSUE TITLE
 package ‘taskscheduleR’ is not available (for R version 4.0.0)

### ISSUE THREAD

**Issue by philipgladwin** [jwijffels/taskscheduleR#76]
When I run the install package code for taskscheduleR in https://rstudio.cloud/ running R 4.0.0
I receive the following error

> install.packages("taskscheduleR")
Installing package into ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘taskscheduleR’ is not available (for R version 4.0.0)

Using a Chrome browser to connect to https://rstudio.cloud/.

I change the version of R from 4.0.0 to 3.6.3 (say) and still get the same error.

Could you investigate?

Installing the package and running the add-in works fine on my Windows PC running RStudio locally.

Thank you,
Phil,

**Comment by philipgladwin** [comment]
Sorry,  my mistake was using taskscheduleR rather than 
install.packages("cronR")
CronR works.
Sorry!
Phil,

**Comment by jwijffels** [comment]
cronR is for Linux, taskscheduleR is for Windows
