### ISSUE TITLE
Citing taskscheduleR in a journal article

### ISSUE THREAD

**Issue by fboehm** [jwijffels/taskscheduleR#78]
Hi, How may I cite your `taskscheduleR` in a journal article? I didn't see a CITATION file in your package. Thank you!

**Comment by jwijffels** [comment]
Just type `citation("taskscheduleR")` and you'll see the default citation for all R packages which have no CITATION file

**Comment by fboehm** [comment]
Can you just print the citation here? i'm unable to install it. 

thanks!

**Comment by jwijffels** [comment]
```
> citation("taskscheduleR")

To cite package ‘taskscheduleR’ in publications use:

  Jan Wijffels and Oliver Belmans (2018). taskscheduleR: Schedule R Scripts and Processes with the Windows Task Scheduler. R
  package version 1.4. https://CRAN.R-project.org/package=taskscheduleR

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {taskscheduleR: Schedule R Scripts and Processes with the Windows Task Scheduler},
    author = {Jan Wijffels and Oliver Belmans},
    year = {2018},
    note = {R package version 1.4},
    url = {https://CRAN.R-project.org/package=taskscheduleR},
  }

```

**Comment by fboehm** [comment]
Thank you so much!! I want to point readers of my manuscript to your package as a way of automating tasks from R with a Windows machine. i don't own a Windows machine, so I couldn't install your package.
