### ISSUE TITLE
Argument Access Isssue

### ISSUE THREAD

**Issue by Kaushikbharat** [jwijffels/taskscheduleR#80]
Unable to access the arguments passed to rscript_args inside the taskscheduleR_create function in the script which needs to be scheduled.

**Comment by jwijffels** [comment]
Why not?

**Comment by Kaushikbharat** [comment]
I tried accessing it as
rscript_args[1]
rscript_args[2] in my scheduled rscript, but it always halts the execution, it seems I am doing something wrong.

**Comment by jwijffels** [comment]
Look at the example script. It shows that https://github.com/bnosac/taskscheduleR/blob/master/inst/extdata/helloworld.R

**Comment by Kaushikbharat** [comment]
Got it, Thanks for the very quick response.
