### ISSUE TITLE
Question - Why copy Rscript to a new location

### ISSUE THREAD

**Issue by vidarsumo** [jwijffels/taskscheduleR#86]
Hello and thank you for a wonderful package.

I have one question. When scheduling an RScript I have to select a location where RScripts  will be copied to schedule

![image](https://user-images.githubusercontent.com/69507559/140537693-f0aa9d26-41d3-41c9-9a99-4cfaafa28a09.png)

What is considered as a best practice here?
Normally I change this location to where the RScript is located right now and I find it strange, if the RScript is a part of a larger project to copy this script to another location.

**Comment by jwijffels** [comment]
The logic is to put the script at a deployment location. 
If you don't want this behaviour, select the Rscript repo the same location as where your script is located or use the functions taskscheduler_create directly without the RStudio addin
Best practices depend on your own way of structuring your code. Up to you.
