### ISSUE TITLE
Error in taskscheduler_ls()

### ISSUE THREAD

**Issue by marco-vene** [jwijffels/taskscheduleR#9]
Hi,

I am not able to run the taskscheduler_ls() function, I get an error related to the fread function of data.table. 

Error in data.table::fread(f) : 
  Expected sep (' ') but new line, EOF (or other non printing character) ends field 4 when detecting types (   first): 
ERRORE: impossibile caricare l'attivit…: ATKOSD2

In addition: Warning message:
In data.table::fread(f) :
  Starting data input on line 2 and discarding line 1 because it has too few or too many items to be column names or data: ERRORE: impossibile caricare l'attivit…: Adobe Acrobat Update Task

I could correctly schedule and run the script, but I do not know how to view all scheduled tasks with this issue with taskscheduler_ls().

Thanks for helping and for the awesome package!

**Comment by jwijffels** [comment]
Thanks for the message. Is that italian 'impossibile caricare l'attivit…: ATKOSD2'? 
Can you indicate what the following gives on your computer?

```
taskscheduler_ls <- function(...){
  cmd <- sprintf('schtasks /Query /FO CSV /V')
  x <- system(cmd, intern = TRUE)
  f <- tempfile()
  writeLines(x, f)
  x <- data.table::fread(f, ...)
  x <- data.table::setDF(x)
  try(x$TaskName <- gsub("^\\\\", "", x$TaskName), silent = TRUE)
  on.exit(file.remove(f))
  x
}
str(taskscheduler_ls(sep = ","))
```

**Comment by marco-vene** [comment]
Hi,

Thanks for the quick reply. It is indeed Italian. Here is the result of the code you sent me. Still in Italian. :(

'data.frame':   201 obs. of  1 variable:
 $ ERRORE: impossibile caricare l'attivit…: Adobe Acrobat Update Task: chr  "ERRORE: L'immagine dell'attivit… Š danneggiata o Š stata manomessa." "\nERRORE: impossibile caricare l'attivit…: ATKOSD2" "ERRORE: L'immagine dell'attivit… Š danneggiata o Š stata manomessa." "\nERRORE: impossibile caricare l'attivit…: CreateChoiceProcessTask" ...

**Comment by jwijffels** [comment]
Can you show me the output of 

```
cmd <- sprintf('schtasks /Query /FO CSV /V')
x <- system(cmd, intern = TRUE, ignore.stderr = TRUE)
f <- tempfile()
writeLines(x, f)
readLines(f, n = 3)
```

**Comment by jwijffels** [comment]
I'm closing this due to no more replies.
