### ISSUE TITLE
Multiple tasks running once

### ISSUE THREAD

**Issue by stevehighuk** [jwijffels/taskscheduleR#91]
I am trying to run multiple tasks throughout the day depending on events during the day. In my case they are horse races. I start each one 15 minutes before certain races and they will run until the race is over. They are scheduled with a task run in the morning that calls taskscheduler_create one time for each race of interest. All of that works fine. However, if the events I set up overlap (ie are within 15 minutes of each other) then the second one will fail, presumably because it cannot write to the same log file. Could we have a way of controlling the name of the log file so I can have one for each instance running?

**Comment by jwijffels** [comment]
Question on log files was also put here #87

**Comment by stevehighuk** [comment]
Thanks

**Comment by jwijffels** [comment]
Closing. Feel free to comment or provide a solution at #87
