### ISSUE TITLE
TaskSchedule Location

### ISSUE THREAD

**Issue by msgoussi** [jwijffels/taskscheduleR#92]
Hi..
When I use taskscheduler_create, it saves the task in "C:\Windows\System32\Tasks".

Is it possible to save in under "C:\Windows\System32\Tasks\Test", so it will be user to navigate.

![image](https://user-images.githubusercontent.com/18138496/177564608-4bf89fdd-dec8-4789-aec8-cbe618ce46cb.png)

**Comment by jwijffels** [comment]
this R package uses schtasks.exe to schedule the task
you can pass the user or an xml file to it if that helps you

**Comment by msgoussi** [comment]
My question is when I use taskscheduler_create, is there any argument to pass the location C:\Windows\System32\Tasks\Test so it would easier view all user tasks under one folder.

**Comment by jwijffels** [comment]
You can pass on an xml file containing all possible taskscheduler settings in argument `schtasks_extra` of `taskscheduler_create`.
R package `taskscheduleR` passes thing on to `schtasks.exe` https://docs.microsoft.com/en-us/windows/win32/taskschd/schtasks
So you can do it if you understand the xml structure. Google schtasks.exe xml to find out how that task looks like or export a task scheduled with `taskscheduleR` in xml to see what it looks like

**Comment by msgoussi** [comment]
It seems that you misunderstood my point.
However i figured out how to create Task under specific folder

myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")
taskscheduler_create(taskname = "**Test\\myfancyscript"**, rscript = myscript, 
 schedule = "ONCE", starttime = runon)

**Comment by jwijffels** [comment]
> However i figured out how to create Task under specific folder

Good to hear that.
