### ISSUE TITLE
 taskscheduleR when the computer is turned off

### ISSUE THREAD

**Issue by swaheera** [jwijffels/taskscheduleR#99]
I am following this tutorial here: https://cran.r-project.org/web/packages/taskscheduleR/vignettes/taskscheduleR.html

Suppose I make the following task:

```
library(taskscheduleR)
myscript <- system.file("extdata", "helloworld.R", package = "taskscheduleR")

## Run every 5 minutes, starting from 10:40
taskscheduler_create(taskname = "myfancyscript_5min", rscript = myscript,
                     schedule = "MINUTE", starttime = "10:40", modifier = 5)

```

If I turn my computer off and then turn my computer back on - will this task still run every 5 minutes? Or will I need to open R Studio again and re-write the above code?

Thanks!

**Comment by jwijffels** [comment]
It will not run when your computer is off but will run again if your computer is on.
